### PR TITLE
Quick fix for create_partial_from_selection

### PR DESCRIPTION
**Pull request by matthewlehner**
There were a couple of 'pretty' single quotes in the file which were causing some grief. I've replaced them with normal looking ones.

### CODE REVIEW

**Comment by infininight** [comment]
This displays just fine here, what problems are you seeing with this?

**Comment by matthewlehner** [comment]
Seems like it was an issue with my setup. Uhhhhg.

**Comment by carlosbrando** [comment]
@infininight, are you using wich ruby version? I have the same error here using Ruby 1.9.2.

**Comment by infininight** [comment]
I installed 1.9.2 to test this and it does cause an error; adding the encoding comment fixes it so this is the solution I'll look at adding to all the scripts in the bundle.

**Pull request merged**
